### ISSUE TITLE
Input image exceeds pixel limit

### ISSUE THREAD

**Issue by thecoffeebin** [rubikscraft/Picsur#107]
When uploading a large GIF file (11Mb) the image preview is broken and I found the following error in the log:

```
picsur           | [Nest] 18  - 12/15/2024, 5:12:44 PM    WARN [SharpWrapper34400] Worker error: Error: Input image exceeds pixel limit
picsur           |     at Sharp.toBuffer (/picsur/node_modules/.pnpm/sharp@0.33.5/node_modules/sharp/lib/output.js:163:17)
picsur           |     at UniversalSharpOut (file:///picsur/backend/dist/workers/sharp/universal-sharp.js:69:40)
picsur           |     at SharpWorker.finish (file:///picsur/backend/dist/workers/sharp/sharp.worker.js:62:34)
picsur           |     at SharpWorker.messageHandler (file:///picsur/backend/dist/workers/sharp/sharp.worker.js:34:18)
picsur           |     at process.emit (node:events:519:28)
picsur           |     at emit (node:internal/child_process:951:14)
picsur           |     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
picsur           |
picsur           | [Nest] 18  - 12/15/2024, 5:12:44 PM   ERROR [MainExceptionFilter] (162.158.192.152 -> GET /i/4e838aa1-fc6b-4853-bcd3-8593caf59e4e.gif?width=1920&shrinkonly=yes) InternalFailure: Worker closed
``` 

The GIF is attached below to help you reproduce this issue.

[time-animated.zip](https://github.com/user-attachments/files/18144011/time-animated.zip)

As a side note I've seen online solution to this i.e. adding “limitInputPixels: false" or "limitInputPixels: 0" to the sharpworker or something but I don't know how ;)

**Comment by CaramelFur** [comment]
Hmm, thanks for the issue, I'll look into it
